#!/bin/bash

# Format Rust files
rs_files=$(git diff --cached --name-only --diff-filter=ACM "*.rs" | tr '\n' ' ')

if [ -n "$rs_files" ] ; then
  echo "$rs_files" | cargo fmt
  echo "$rs_files" | xargs git add
fi

exit 0
